import { useEffect, useMemo, useState } from "react";
import { FiBarChart2, FiBookOpen, FiCheck, FiChevronLeft, FiChevronRight, FiDownload, FiEdit2, FiEye, FiFile, FiFileText, FiFilter, FiGlobe, FiImage, FiInfo, FiPlus, FiSearch, FiSend, FiStar, FiTag, FiTrash2, FiUploadCloud, FiUsers, FiVideo, FiX, FiZap } from "react-icons/fi";
import { toast } from "sonner";
import api from "../../services/api";
import { State } from "../../components/common/ModuleUI";

const PAGE_SIZE = 6;
const typeIcons = { documento: FiFileText, pdf: FiFile, imagen: FiImage, video: FiVideo, interactivo: FiZap };
const labels = { documento: "Documento", pdf: "PDF", imagen: "Imagen", video: "Video", interactivo: "Interactivo", bajo: "Básico", medio: "Intermedio", alto: "Avanzado", general: "General", publicada: "Publicada", borrador: "Borrador" };
const tones = ["purple", "blue", "green", "orange", "rose"];
const normalizeGuide = (item, index) => ({ ...item, tipo: item.tipo_recurso || "documento", alcance: Number(item.envios || 0) ? "Específica" : "General", visualizaciones: Number(item.completadas || 0), envios: Number(item.envios || 0), estado: item.estado || "borrador", _tone: tones[index % tones.length] });
const formatDate = (value) => value ? new Intl.DateTimeFormat("es-HN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Sin fecha";

function AssignmentModal({ guides, participants, initialGuide, saving, onClose, onSubmit }) {
  const [guideId, setGuideId] = useState(initialGuide?.id_guia || ""), [participantSearch, setParticipantSearch] = useState(""), [riskFilter, setRiskFilter] = useState(""), [chosen, setChosen] = useState(new Set()), [message, setMessage] = useState("");
  const guide = guides.find((item) => item.id_guia === guideId);
  const shownParticipants = participants.filter((item) => { const query = participantSearch.trim().toLowerCase(), name = `${item.nombre_completo || ""} ${item.correo || item.email || ""}`.toLowerCase(); return (!query || name.includes(query)) && (!riskFilter || (item.clasificacion_riesgo || "sin_evaluar") === riskFilter); });
  const toggle = (id) => setChosen((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const initials = (name = "") => name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "U";
  return <div className="moduleModal assignmentOverlay" onClick={onClose}><form className="moduleModalContent assignmentModal" onSubmit={onSubmit} onClick={(event) => event.stopPropagation()}>
    <header className="assignmentHeader"><span className="assignmentHeroIcon"><FiBookOpen /></span><div><span>ASIGNACIÓN PERSONALIZADA</span><h2>Asignar guía</h2><p>Selecciona una guía, elige los participantes y agrega un mensaje personalizado.</p></div><button type="button" onClick={onClose} aria-label="Cerrar"><FiX /></button></header>
    <section className="assignmentStep"><div className="assignmentStepTitle"><b>1</b><h3>Selecciona una guía</h3></div><label className="assignmentGuideSelect"><FiBookOpen /><select name="guia" value={guideId} onChange={(event) => setGuideId(event.target.value)} required><option value="" disabled>Selecciona una guía</option>{guides.map((item) => <option value={item.id_guia} key={item.id_guia}>{item.titulo}</option>)}</select></label></section>
    <section className="assignmentStep"><div className="assignmentStepTitle"><b>2</b><h3>Elige los participantes</h3><span>Seleccionados: {chosen.size} de {participants.length}</span></div><div className="assignmentPeopleGrid"><div><div className="assignmentPeopleFilters"><label><FiSearch /><input value={participantSearch} onChange={(event) => setParticipantSearch(event.target.value)} placeholder="Buscar participante..." /></label><select value={riskFilter} onChange={(event) => setRiskFilter(event.target.value)}><option value="">Todos los riesgos</option><option value="sin_evaluar">Sin evaluar</option><option value="bajo">Bajo</option><option value="medio">Medio</option><option value="alto">Alto</option></select></div><fieldset className="assignmentPeopleList">{shownParticipants.length ? shownParticipants.map((item) => { const risk = item.clasificacion_riesgo || "sin_evaluar"; return <label key={item.id_participante}><input type="checkbox" name="participantes" value={item.id_participante} checked={chosen.has(item.id_participante)} onChange={() => toggle(item.id_participante)} /><span className="assignmentAvatar">{initials(item.nombre_completo)}</span><span className="assignmentPerson"><strong>{item.nombre_completo || "Participante"}</strong><small>{item.correo || item.email || "Sin correo registrado"}</small></span><em className={`assignmentRisk ${risk}`}>{risk === "sin_evaluar" ? "Sin evaluar" : labels[risk]}</em></label>; }) : <p className="assignmentEmpty">No hay participantes con este filtro.</p>}</fieldset></div><aside className="assignmentPreview"><div><span className="assignmentHeroIcon"><FiBookOpen /></span><div><strong>Vista previa de la guía</strong><p>{guide ? "Recurso seleccionado" : "Selecciona una guía para ver su información."}</p></div></div><section>{guide ? <><span className="guideFormat">{labels[guide.tipo]}</span><h4>{guide.titulo}</h4><p>{guide.descripcion || "Sin descripción."}</p><small>{guide.categoria} · {labels[guide.nivel_recomendado]}</small></> : <><FiFileText /><p>Aquí verás el título, descripción y nivel de la guía seleccionada.</p></>}</section></aside></div></section>
    <section className="assignmentStep"><div className="assignmentStepTitle"><b>3</b><h3>Mensaje personalizado</h3></div><textarea name="mensaje" value={message} maxLength="500" onChange={(event) => setMessage(event.target.value)} rows="4" placeholder="Explica por qué le recomiendas esta guía..." /><small className="assignmentCounter">{message.length}/500</small></section>
    <footer className="assignmentFooter"><div><FiZap /><span><strong>Consejo</strong><small>Un mensaje personalizado ayuda al participante a comprender por qué debe revisar la guía.</small></span></div><button type="button" className="guideOutlineButton" onClick={onClose}>Cancelar</button><button disabled={saving || !guideId || !chosen.size} className="guidePrimaryButton"><FiSend /> {saving ? "Asignando..." : "Asignar guía"}</button></footer>
  </form></div>;
}

function GuideEditorModal({ guide, saving, onClose, onSubmit }) {
  const editing = Boolean(guide), [title, setTitle] = useState(guide?.titulo || ""), [description, setDescription] = useState(guide?.descripcion || ""), [content, setContent] = useState(guide?.contenido || ""), [fileName, setFileName] = useState(guide?.archivo_nombre || "");
  return <div className="moduleModal guideEditorOverlay" onClick={onClose}><form className="moduleModalContent guideEditorModal" onSubmit={onSubmit} onClick={(event) => event.stopPropagation()}>
    <header className="guideEditorHeader"><span className="guideEditorHero"><FiBookOpen /></span><div><span>{editing ? "EDITAR RECURSO EDUCATIVO" : "NUEVO RECURSO EDUCATIVO"}</span><h2>{editing ? "Editar guía" : "Crear guía"}</h2><p>{editing ? "Actualiza el contenido guardado en la base de datos." : "Se guardará en la base de datos y después podrás asignarla a participantes."}</p></div><button type="button" onClick={onClose} aria-label="Cerrar"><FiX /></button></header>
    <div className="guideEditorGrid"><section className="guideEditorFields"><label><strong>Título de la guía</strong><span className="guideFieldControl"><FiBookOpen /><input name="titulo" value={title} maxLength="100" onChange={(event) => setTitle(event.target.value)} required placeholder="Ej. Navegación segura en internet" /></span><small>{title.length}/100</small></label><label><strong>Descripción</strong><span className="guideFieldControl textarea"><FiFileText /><textarea name="descripcion" value={description} maxLength="500" onChange={(event) => setDescription(event.target.value)} rows="4" placeholder="Qué aprenderá el usuario con esta guía..." /></span><small>{description.length}/500</small></label><label><strong>Contenido escrito</strong><span className="guideFieldControl textarea"><FiEdit2 /><textarea name="contenido" value={content} maxLength="50000" onChange={(event) => setContent(event.target.value)} rows="4" placeholder="Escribe aquí el contenido si la guía no depende solamente de un archivo..." /></span></label><div className="guideEditorPair"><label><strong>Categoría</strong><span className="guideFieldControl"><FiTag /><select name="categoria" defaultValue={guide?.categoria || "Privacidad"}><option>Privacidad</option><option>Contraseñas</option><option>Phishing</option><option>Redes</option><option>Autenticación</option><option>Dispositivos</option><option>Otros</option></select></span></label><label><strong>Nivel</strong><span className="guideFieldControl"><FiBarChart2 /><select name="nivel_recomendado" defaultValue={guide?.nivel_recomendado || "general"}><option value="general">General</option><option value="bajo">Básico</option><option value="medio">Intermedio</option><option value="alto">Avanzado</option></select></span></label></div><label><strong>Formato</strong><span className="guideFieldControl"><FiFile /><select name="tipo_recurso" defaultValue={guide?.tipo || "documento"}><option value="documento">Documento</option><option value="pdf">PDF</option><option value="imagen">Imagen</option><option value="video">Video</option><option value="interactivo">Interactivo</option></select></span><small>Define el tipo de contenido para una mejor organización.</small></label></section>
      <section className="guideEditorFile"><div><h3>Contenido del archivo</h3><p>Opcional si prefieres adjuntar un archivo.</p></div><label className="guideDropzone"><FiUploadCloud /><strong>{fileName || "Arrastra un archivo aquí"}</strong><span>{fileName ? "Haz clic para reemplazarlo" : "o haz clic para seleccionar"}</span><small>PDF, documentos, imágenes o videos<br />Máx. 50 MB</small><input name="archivo" type="file" accept=".pdf,.doc,.docx,image/*,video/mp4,video/webm" onChange={(event) => setFileName(event.target.files?.[0]?.name || guide?.archivo_nombre || "")} /></label><aside className="guideUploadHelp"><FiInfo /><p><strong>¿Qué tipo de contenido puedes subir?</strong><span>Puedes adjuntar guías en PDF, documentos de texto, imágenes o videos relevantes para los participantes.</span></p></aside><fieldset className="guideStatusChoice"><legend>Estado de la guía</legend><label><input type="radio" name="estado" value="borrador" defaultChecked={guide?.estado !== "publicada"} /><span><FiEdit2 /><p><strong>Borrador</strong><small>Solo será visible para administradores.</small></p></span></label><label><input type="radio" name="estado" value="publicada" defaultChecked={guide?.estado === "publicada"} /><span><FiGlobe /><p><strong>Pública</strong><small>Disponible para todos los usuarios.</small></p></span></label></fieldset></section>
    </div><footer className="guideEditorFooter"><div><FiZap /><p><strong>Consejo</strong><small>Una guía clara con ejemplos y recomendaciones prácticas genera mayor impacto.</small></p></div><button type="button" className="guideOutlineButton" onClick={onClose}>Cancelar</button><button disabled={saving || !title.trim()} className="guidePrimaryButton"><FiCheck /> {saving ? "Guardando..." : editing ? "Guardar cambios" : "Guardar guía"}</button></footer>
  </form></div>;
}

export default function GuidesPage() {
  const [rows, setRows] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [search, setSearch] = useState(""), [category, setCategory] = useState(""), [level, setLevel] = useState(""), [status, setStatus] = useState("");
  const [tab, setTab] = useState("todas"), [page, setPage] = useState(1), [selected, setSelected] = useState(null), [dialog, setDialog] = useState(null), [favorites, setFavorites] = useState(new Set()), [participants, setParticipants] = useState([]), [saving, setSaving] = useState(false);

  useEffect(() => { Promise.all([api.get("/guias/admin"), api.get("/participantes")]).then(([guidesResponse, participantsResponse]) => { setRows((guidesResponse.data.items || []).map(normalizeGuide)); setParticipants(participantsResponse.data.items || []); }).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)); }, []);
  const categories = useMemo(() => [...new Set(rows.map((item) => item.categoria).filter(Boolean))], [rows]);
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase("es"); return rows.filter((item) => { const text = `${item.titulo} ${item.descripcion} ${item.categoria} ${item.tipo}`.toLocaleLowerCase("es"); return (!query || text.includes(query)) && (!category || item.categoria === category) && (!level || item.nivel_recomendado === level) && (!status || item.estado === status) && (tab !== "favoritas" || favorites.has(item.id_guia)); }); }, [rows, search, category, level, status, tab, favorites]);
  useEffect(() => setPage(1), [search, category, level, status, tab]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const published = rows.filter((item) => item.estado === "publicada").length, views = rows.reduce((sum, item) => sum + item.visualizaciones, 0), sent = rows.reduce((sum, item) => sum + item.envios, 0);
  const clearFilters = () => { setSearch(""); setCategory(""); setLevel(""); setStatus(""); };
  const closeDialog = () => { setDialog(null); setSelected(null); };
  const toggleFavorite = (id) => setFavorites((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  async function saveGuide(event) { event.preventDefault(); setSaving(true); try { const form = new FormData(event.currentTarget); if (dialog === "edit") { const { data } = await api.put(`/guias/admin/${selected.id_guia}`, form); setRows((current) => current.map((item, index) => item.id_guia === selected.id_guia ? normalizeGuide(data, index) : item)); toast.success("La guía fue actualizada."); } else { const { data } = await api.post("/guias/admin", form); setRows((current) => [normalizeGuide(data, current.length), ...current]); toast.success("La guía fue guardada en la base de datos."); } setDialog(null); setSelected(null); } catch (requestError) { toast.error(requestError.message); } finally { setSaving(false); } }
  async function sendGuide(event) { event.preventDefault(); const form = new FormData(event.currentTarget), guideId = form.get("guia"), participantIds = form.getAll("participantes"); if (!participantIds.length) return toast.error("Selecciona al menos un participante."); setSaving(true); try { await api.post(`/guias/admin/${guideId}/asignar`, { participantes: participantIds, mensaje: form.get("mensaje") || "" }); setRows((current) => current.map((item) => item.id_guia === guideId ? { ...item, envios: participantIds.length, alcance: "Específica", estado: "publicada" } : item)); closeDialog(); toast.success("La guía fue asignada correctamente."); } catch (requestError) { toast.error(requestError.message); } finally { setSaving(false); } }
  async function removeGuide(item) { if (!window.confirm(`¿Eliminar definitivamente la guía “${item.titulo}”?`)) return; try { await api.delete(`/guias/admin/${item.id_guia}`); setRows((current) => current.filter((guide) => guide.id_guia !== item.id_guia)); toast.success("Guía eliminada."); } catch (requestError) { toast.error(requestError.message); } }
  if (loading) return <State loading />;
  if (error) return <State error={error} />;
  return <div className="guidesAdminPage">
    <div className="guidesActions"><div><strong>Biblioteca de guías</strong><span>Solo se muestran recursos guardados por el administrador.</span></div><button className="guidePrimaryButton" onClick={() => { setSelected(null); setDialog("create"); }}><FiPlus /> Crear o subir guía</button><button className="guideOutlineButton" disabled={!rows.length} onClick={() => setDialog("send")}><FiSend /> Asignar guía</button></div>
    <nav className="guideTabs" aria-label="Vistas de guías"><button className={tab === "todas" ? "active" : ""} onClick={() => setTab("todas")}>Todas las guías</button><button className={tab === "favoritas" ? "active" : ""} onClick={() => setTab("favoritas")}>Favoritas <span>{favorites.size}</span></button></nav>
    <section className="guideMetrics" aria-label="Resumen de guías"><article><span className="guideMetricIcon purple"><FiBookOpen /></span><div><small>Total de guías</small><strong>{rows.length}</strong><p>{published} publicadas</p></div></article><article><span className="guideMetricIcon green"><FiCheck /></span><div><small>Guías enviadas</small><strong>{sent}</strong><p>A participantes</p></div></article><article><span className="guideMetricIcon orange"><FiEye /></span><div><small>Visualizaciones</small><strong>{views.toLocaleString("es-HN")}</strong><p>Total de vistas</p></div></article><article><span className="guideMetricIcon blue"><FiStar /></span><div><small>Favoritas</small><strong>{favorites.size}</strong><p>Marcadas por ti</p></div></article></section>
    <section className="moduleCard guidesTableCard"><div className="guidesToolbar"><label className="guideSearch"><FiSearch /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por título, descripción o tipo..." /></label><div className="guideFilters"><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Todas las categorías</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select value={level} onChange={(event) => setLevel(event.target.value)}><option value="">Todos los niveles</option><option value="bajo">Básico</option><option value="medio">Intermedio</option><option value="alto">Avanzado</option><option value="general">General</option></select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos los estados</option><option value="publicada">Publicada</option><option value="borrador">Borrador</option></select><button className="guideClearButton" onClick={clearFilters}><FiFilter /> Limpiar</button></div></div>
      <State empty={!filtered.length} emptyText="No hay guías que coincidan con los filtros." />
      {!!visible.length && <div className="moduleTableWrap"><table className="moduleTable guidesTable"><thead><tr><th>Guía</th><th>Formato</th><th>Audiencia</th><th>Nivel</th><th>Completadas</th><th>Asignadas</th><th>Fecha</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{visible.map((item) => { const TypeIcon = typeIcons[item.tipo] || FiFileText; return <tr key={item.id_guia}><td><div className="guideIdentity"><span className={`guideTypeIcon ${item._tone}`}><TypeIcon /></span><div><strong>{item.titulo}</strong><small>{item.descripcion || "Sin descripción"}</small></div></div></td><td><span className="guideFormat">{labels[item.tipo]}</span></td><td><span className={`guideAudience ${item.alcance === "Específica" ? "specific" : ""}`}>{item.alcance === "Específica" ? <FiUsers /> : <FiBookOpen />}{item.alcance}</span></td><td><span className={`guideLevel ${item.nivel_recomendado}`}>{labels[item.nivel_recomendado]}</span></td><td>{item.visualizaciones}</td><td>{item.envios}</td><td>{formatDate(item.fecha_creacion)}</td><td><span className={`guideStatus ${item.estado}`}>{labels[item.estado]}</span></td><td><div className="guideRowActions"><button aria-label="Editar guía" title="Editar" onClick={() => { setSelected(item); setDialog("edit"); }}><FiEdit2 /></button><button aria-label="Asignar guía" title="Asignar" onClick={() => { setSelected(item); setDialog("send"); }}><FiSend /></button><button aria-label="Marcar favorita" title="Favorita" className={favorites.has(item.id_guia) ? "favorite" : ""} onClick={() => toggleFavorite(item.id_guia)}><FiStar /></button><button className="guideDeleteButton" aria-label="Eliminar guía" title="Eliminar" onClick={() => removeGuide(item)}><FiTrash2 /></button></div></td></tr>; })}</tbody></table></div>}
      {!!filtered.length && <footer className="guidesPagination"><span>Mostrando {(page - 1) * PAGE_SIZE + 1} a {Math.min(page * PAGE_SIZE, filtered.length)} de {filtered.length} guías</span><div><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}><FiChevronLeft /></button><strong>{page}</strong><button disabled={page === pageCount} onClick={() => setPage((value) => value + 1)}><FiChevronRight /></button></div></footer>}
    </section>
    {selected && !dialog && <div className="moduleModal" onClick={() => setSelected(null)}><article className="moduleModalContent guidePreviewModal" onClick={(event) => event.stopPropagation()}><button className="guideModalClose" onClick={() => setSelected(null)} aria-label="Cerrar"><FiX /></button><span className={`guideTypeIcon ${selected._tone}`}>{(() => { const Icon = typeIcons[selected.tipo] || FiFileText; return <Icon />; })()}</span><p className="guidePreviewMeta">{selected.categoria} · {labels[selected.nivel_recomendado]} · {labels[selected.tipo]}</p><h2>{selected.titulo}</h2><p>{selected.descripcion}</p>{selected.contenido && <div className="guidePreviewBody">{selected.contenido}</div>}<footer>{selected.archivo_url && <a className="guideOutlineButton" href={selected.archivo_url} target="_blank" rel="noreferrer"><FiDownload /> Abrir archivo</a>}<button className="guidePrimaryButton" onClick={() => setDialog("send")}><FiSend /> Asignar guía</button></footer></article></div>}
    {(dialog === "create" || dialog === "edit") && <GuideEditorModal guide={dialog === "edit" ? selected : null} saving={saving} onClose={closeDialog} onSubmit={saveGuide} />}
    {dialog === "send" && <AssignmentModal guides={rows} participants={participants} initialGuide={selected} saving={saving} onClose={closeDialog} onSubmit={sendGuide} />}
  </div>;
}
