import { useEffect, useMemo, useState } from "react";
import api from "../../services/api";
import { Metrics, PageHeading, State } from "../../components/common/ModuleUI";

export default function ParticipantsPage(){
 const [rows,setRows]=useState([]),[stats,setStats]=useState({}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[city,setCity]=useState(""),[education,setEducation]=useState(""),[risk,setRisk]=useState(""),[selected,setSelected]=useState(null);
 useEffect(()=>{api.cachedGet("/participantes").then(({data})=>{setRows(data.items||[]);setStats(data.estadisticas||{})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>rows.filter(r=>(!search||r.nombre_completo?.toLowerCase().includes(search.toLowerCase()))&&(!city||r.ciudad===city)&&(!education||r.nivel_educativo===education)&&(!risk||r.clasificacion_riesgo===risk)),[rows,search,city,education,risk]);
 return <><PageHeading eyebrow="Análisis" title="Participantes">Consulta usuarios, estado de evaluación y último nivel de riesgo.</PageHeading><Metrics items={[{label:"Participantes",value:stats.total},{label:"Evaluados",value:stats.evaluados},{label:"Pendientes",value:stats.pendientes},{label:"Riesgo alto",value:stats.riesgo_alto},{label:"Promedio",value:stats.promedio_riesgo}]}/><State loading={loading} error={error}/>{!loading&&!error&&<section className="moduleCard"><div className="moduleToolbar"><input placeholder="Buscar por nombre" value={search} onChange={e=>setSearch(e.target.value)}/><select value={city} onChange={e=>setCity(e.target.value)}><option value="">Todas las ciudades</option>{[...new Set(rows.map(x=>x.ciudad).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select><select value={education} onChange={e=>setEducation(e.target.value)}><option value="">Todos los niveles</option>{[...new Set(rows.map(x=>x.nivel_educativo).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">Todos los riesgos</option><option value="sin_evaluar">Sin evaluar</option><option value="bajo">Bajo</option><option value="medio">Medio</option><option value="alto">Alto</option></select></div><State empty={!filtered.length} emptyText="No hay participantes que coincidan con los filtros."/>{filtered.length>0&&<div className="moduleTableWrap"><table className="moduleTable"><thead><tr><th>Nombre</th><th>Edad</th><th>Ciudad</th><th>Nivel educativo</th><th>Encuestas</th><th>Puntaje</th><th>Riesgo</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id_participante}><td>{r.nombre_completo}</td><td>{r.edad??"—"}</td><td>{r.ciudad||"—"}</td><td>{r.nivel_educativo||"—"}</td><td>{r.encuestas_realizadas}</td><td>{r.puntaje_riesgo??"—"}</td><td>{r.clasificacion_riesgo?.replace("_"," ")}</td><td><button onClick={()=>setSelected(r)}>Detalle</button></td></tr>)}</tbody></table></div>}</section>}{selected&&<div className="moduleModal" onClick={()=>setSelected(null)}><article className="moduleModalContent" onClick={e=>e.stopPropagation()}><h2>{selected.nombre_completo}</h2><div className="moduleGrid"><p><b>Género:</b> {selected.genero||"No registrado"}</p><p><b>Ciudad:</b> {selected.ciudad||"No registrada"}</p><p><b>Conocimiento:</b> {selected.nivel_conocimiento||"Sin evaluar"}</p><p><b>Phishing:</b> {selected.reconoce_phishing||"Sin evaluar"}</p><p><b>Antivirus:</b> {selected.estado_antivirus||"Sin evaluar"}</p><p><b>Contraseñas:</b> {selected.reutiliza_contrasenas||"Sin evaluar"}</p><p><b>Conexión:</b> {selected.tipo_conexion||"Sin evaluar"}</p></div><p>{selected.observacion||"Sin evaluación registrada."}</p><button onClick={()=>setSelected(null)}>Cerrar</button></article></div>}</>;
}
