import { useEffect, useState } from "react";
import { FiArrowLeft, FiClipboard, FiEdit3, FiPlus, FiSend, FiUsers, FiX } from "react-icons/fi";
import { toast } from "sonner";
import api from "../../services/api";
import { State } from "../../components/common/ModuleUI";

const blankQuestion = () => ({ texto: "", tipo: "opcion", requerida: true, opciones: [{ etiqueta: "", puntos: 0 }, { etiqueta: "", puntos: 0 }] });
const formatDate = (value) => value ? new Date(value).toLocaleString("es-HN", { dateStyle: "medium", timeStyle: "short" }) : "—";

export default function SurveysPage() {
  const [surveys, setSurveys] = useState([]), [selected, setSelected] = useState(null), [mode, setMode] = useState("list"), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const schemaMissing = error.includes("encuestas_dinamicas") || error.includes("schema cache");
  const [form, setForm] = useState({ titulo: "", descripcion: "", preguntas: [blankQuestion()] });
  const load = () => api.cachedGet("/encuestas-configurables", {}, 0).then(({ data }) => setSurveys(data.items || [])).catch((e) => setError(e.message)).finally(() => setLoading(false));
  useEffect(load, []);
  const open = async (id) => { setLoading(true); try { const { data } = await api.cachedGet(`/encuestas-configurables/${id}`, {}, 0); setSelected(data); setMode("detail"); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const question = (index, values) => setForm((current) => ({ ...current, preguntas: current.preguntas.map((item, itemIndex) => itemIndex === index ? { ...item, ...values } : item) }));
  const option = (qIndex, oIndex, values) => question(qIndex, { opciones: form.preguntas[qIndex].opciones.map((item, itemIndex) => itemIndex === oIndex ? { ...item, ...values } : item) });
  const changeType = (index, tipo) => question(index, { tipo, opciones: tipo === "si_no" ? [{ etiqueta: "Sí", puntos: 0 }, { etiqueta: "No", puntos: 0 }] : tipo === "escala" ? [1,2,3,4,5].map((value) => ({ etiqueta: String(value), puntos: value - 1 })) : tipo === "texto" ? [] : [{ etiqueta: "", puntos: 0 }, { etiqueta: "", puntos: 0 }] });
  async function create(event) { event.preventDefault(); try { const payload = { ...form, preguntas: form.preguntas.map((item) => ({ ...item, opciones: item.opciones.filter((value) => value.etiqueta.trim()) })) }; await api.post("/encuestas-configurables", payload); toast.success("Encuesta creada como borrador."); setForm({ titulo: "", descripcion: "", preguntas: [blankQuestion()] }); setMode("list"); load(); } catch (e) { toast.error(e.message); } }
  async function state(value) { try { await api.patch(`/encuestas-configurables/${selected.id}/estado`, { estado: value }); toast.success(`Encuesta ${value}.`); await open(selected.id); load(); } catch (e) { toast.error(e.message); } }

  if (mode === "create") return <form className="surveyBuilder" onSubmit={create}><div className="surveyBuilderHeader"><button type="button" onClick={() => setMode("list")}><FiArrowLeft /> Volver</button><div><span>Constructor</span><h2>Nueva encuesta</h2><p>Define las preguntas en el orden en que las verá el usuario.</p></div><button className="moduleButton" type="submit"><FiClipboard /> Guardar borrador</button></div><section className="moduleCard surveyBuilderMeta"><label>Título<input value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} required /></label><label>Descripción<textarea value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} rows="3" /></label></section><div className="surveyQuestionList">{form.preguntas.map((item, index) => <section className="moduleCard surveyQuestionEditor" key={index}><div className="surveyQuestionNumber">{index + 1}</div><button className="surveyQuestionRemove" type="button" disabled={form.preguntas.length === 1} onClick={() => setForm({ ...form, preguntas: form.preguntas.filter((_, i) => i !== index) })}><FiX /></button><label>Pregunta<input value={item.texto} onChange={(e) => question(index, { texto: e.target.value })} required /></label><div className="surveyQuestionSettings"><label>Tipo<select value={item.tipo} onChange={(e) => changeType(index, e.target.value)}><option value="opcion">Opción única</option><option value="si_no">Sí / No</option><option value="escala">Escala 1–5</option><option value="texto">Respuesta abierta</option></select></label><label className="surveyRequired"><input type="checkbox" checked={item.requerida} onChange={(e) => question(index, { requerida: e.target.checked })} /> Obligatoria</label></div>{item.opciones.length > 0 && <div className="surveyOptions"><span>Respuestas y puntos de riesgo</span>{item.opciones.map((answer, answerIndex) => <div key={answerIndex}><input placeholder={`Opción ${answerIndex + 1}`} value={answer.etiqueta} disabled={item.tipo === "si_no" || item.tipo === "escala"} onChange={(e) => option(index, answerIndex, { etiqueta: e.target.value })} required /><input aria-label="Puntos" type="number" min="0" max="100" value={answer.puntos} onChange={(e) => option(index, answerIndex, { puntos: Number(e.target.value) })} /></div>)}{item.tipo === "opcion" && <button type="button" onClick={() => question(index, { opciones: [...item.opciones, { etiqueta: "", puntos: 0 }] })}><FiPlus /> Añadir opción</button>}</div>}</section>)}</div><button className="surveyAddQuestion" type="button" onClick={() => setForm({ ...form, preguntas: [...form.preguntas, blankQuestion()] })}><FiPlus /> Añadir pregunta</button></form>;

  if (mode === "detail" && selected) return <><div className="surveyDetailHeader"><button onClick={() => setMode("list")}><FiArrowLeft /> Encuestas</button><div><span className={`surveyState ${selected.estado}`}>{selected.estado}</span><h2>{selected.titulo}</h2><p>{selected.descripcion}</p></div><div>{selected.estado === "borrador" && <button className="moduleButton" onClick={() => state("publicada")}><FiSend /> Publicar</button>}{selected.estado === "publicada" && <button onClick={() => state("cerrada")}>Cerrar encuesta</button>}</div></div><section className="surveyDefinitionGrid"><article className="moduleCard"><FiEdit3 /><strong>{selected.preguntas.length}</strong><span>Preguntas ordenadas</span></article><article className="moduleCard"><FiUsers /><strong>{selected.aplicaciones?.length || 0}</strong><span>Personas encuestadas</span></article></section><section className="moduleCard participantsCard"><div className="surveyResponsesTitle"><h3>Personas que respondieron</h3><p>Ordenadas por fecha de aplicación.</p></div><State empty={!selected.aplicaciones?.length} emptyText="Aún no hay respuestas para esta encuesta." />{!!selected.aplicaciones?.length && <div className="moduleTableWrap"><table className="moduleTable participantsTable"><thead><tr><th>Orden</th><th>Usuario</th><th>Fecha</th><th>Puntaje</th><th>Riesgo</th><th>Evaluación</th></tr></thead><tbody>{selected.aplicaciones.map((row, index) => <tr key={row.id}><td>#{index + 1}</td><td><strong>{row.nombre_usuario}</strong></td><td>{formatDate(row.fecha_respuesta)}</td><td>{row.puntaje}/{row.puntaje_maximo}</td><td><span className={`riskBadge ${row.clasificacion_riesgo}`}>{row.clasificacion_riesgo}</span></td><td><button className="participantDetailButton" onClick={() => setSelected({ ...selected, activeApplication: row })}>Ver respuestas</button></td></tr>)}</tbody></table></div>}</section>{selected.activeApplication && <div className="moduleModal" onClick={() => setSelected({ ...selected, activeApplication: null })}><article className="moduleModalContent participantModal" onClick={(e) => e.stopPropagation()}><button className="participantModalClose" onClick={() => setSelected({ ...selected, activeApplication: null })}><FiX /></button><h2>{selected.activeApplication.nombre_usuario}</h2><p>{selected.activeApplication.observacion}</p><div className="participantDetailGrid">{selected.activeApplication.respuestas.map((answer) => <p key={answer.id_pregunta}><span>{answer.orden}. {answer.pregunta}</span><strong>{String(answer.valor ?? "Sin respuesta")}</strong><small>{answer.puntos} puntos</small></p>)}</div></article></div>}</>;

  return <><section className="surveysHero"><div><span>Encuestas configurables</span><h2>Crea, publica y analiza</h2><p>Cada encuesta conserva sus preguntas, participantes y evaluaciones en orden.</p></div><button className="surveyCreateButton" disabled={schemaMissing} onClick={() => setMode("create")}><FiPlus /> Crear encuesta</button></section>{schemaMissing ? <section className="surveySetupNotice"><strong>Configuración pendiente en Supabase</strong><p>Ejecuta la migración 005_encuestas_dinamicas.sql para habilitar la creación y aplicación de encuestas.</p></section> : <State loading={loading} error={error} />}{!error && <><section className="surveyDefinitionCards">{surveys.map((item) => <button className="surveyDefinitionCard" key={item.id} onClick={() => open(item.id)}><span className={`surveyState ${item.estado}`}>{item.estado}</span><h3>{item.titulo}</h3><p>{item.descripcion || "Sin descripción"}</p><footer><span>{item.total_preguntas} preguntas</span><span>{item.total_respuestas} respuestas</span></footer></button>)}</section><State empty={!loading && !surveys.length} emptyText="No hay encuestas creadas. Comienza creando la primera." /></>}</>;
}
